---
- name: create powershell script
  local_action: template dest="{{ auto_deploy_ps }}" src="{{ auto_deploy_src }}"

- name: run powershell script to create autodeploy rules
  script: "{{ auto_deploy_ps }}"
  register: s_test

- name: debug script
  debug: var=s_test
