---
- name: enable bash on vcenter
  ignore_errors: yes
  local_action:
    module: set_vcsa_sh
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    port: 22
    shell: "/bin/bash"

- name: enable autodeploy service
  service: name=vmware-rbd-watchdog enabled=yes state=restarted

- name: generating zip
  wait_for: timeout=3

- name: zip deploy-tftp files
  shell: 'cd /usr/share/ipxe && tar -cjf /tmp/deploy-tftpd.tbz2 *efi* undion*'

# todo investigate checksum issue
- name: Fetch deploy
  fetch: src=/tmp/deploy-tftpd.tbz2 dest=tmp/deploy-tftpd.tbz2 flat=yes validate_checksum=no
